# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RiNAQM2ZpGWiAdlegCnVVnsTb8xkjbi

KGAT_b9317532b20a904317ac3211038725ed
"""

import os
# Masukkan kredensial Kaggle Anda
os.environ['KAGGLE_USERNAME'] = "Saifuddin Tamam"
os.environ['KAGGLE_KEY'] = "KGAT_b9317532b20a904317ac3211038725ed"

# Download & Unzip
!kaggle datasets download -d andrewmvd/ocular-disease-recognition-odir5k
!unzip -q ocular-disease-recognition-odir5k.zip -d odir_dataset
print("✓ Dataset Siap!")

import pandas as pd
import numpy as np
import os
import cv2
import glob
from sklearn.utils import resample
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pickle

# Load CSV
csv_path = glob.glob('odir_dataset/*.csv')[0]
df = pd.read_csv(csv_path)

# Mapping Label Utama
def get_label(row):
    for label in ['N', 'D', 'G', 'C', 'A', 'H', 'M', 'O']:
        if row[label] == 1: return label
    return 'N'

df['target'] = df.apply(get_label, axis=1)

# Deteksi Folder Gambar
image_dir = 'odir_dataset/preprocessed_images'
df = df[df['filename'].apply(lambda x: os.path.exists(os.path.join(image_dir, x)))].reset_index(drop=True)

# OVERSAMPLING (Penyeimbangan Data)
target_count = 1500
balanced_list = []
for label in ['N', 'D', 'G', 'C', 'A', 'H', 'M', 'O']:
    class_df = df[df['target'] == label]
    resampled = resample(class_df, replace=True, n_samples=target_count, random_state=42)
    balanced_list.append(resampled)

df_balanced = pd.concat(balanced_list)
print("Distribusi Data Baru:\n", df_balanced['target'].value_counts())

# Simpan Label Encoder untuk VS Code nanti
le = LabelEncoder()
df_balanced['label_idx'] = le.fit_transform(df_balanced['target'])
with open('label_encoder_mn.pkl', 'wb') as f:
    pickle.dump(le, f)

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# Fungsi Penajaman Medis (CLAHE)
def apply_clahe_medis(img):
    img = (img * 255).astype(np.uint8) if img.max() <= 1.0 else img.astype(np.uint8)
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8,8))
    l = clahe.apply(l)
    img = cv2.merge([l, a, b])
    return cv2.cvtColor(img, cv2.COLOR_LAB2RGB)

def final_preprocess(img):
    img = apply_clahe_medis(img) # Tajamkan
    return preprocess_input(img) # Normalisasi MobileNetV2

# Split Data
train_df, val_df = train_test_split(df_balanced, test_size=0.15, stratify=df_balanced['target'], random_state=42)

# Generators
datagen = ImageDataGenerator(
    preprocessing_function=final_preprocess,
    rotation_range=20, horizontal_flip=True, zoom_range=0.1
)
val_datagen = ImageDataGenerator(preprocessing_function=final_preprocess)

train_gen = datagen.flow_from_dataframe(
    train_df, directory=image_dir, x_col='filename', y_col='target',
    target_size=(224, 224), batch_size=32, class_mode='categorical'
)

val_gen = val_datagen.flow_from_dataframe(
    val_df, directory=image_dir, x_col='filename', y_col='target',
    target_size=(224, 224), batch_size=32, class_mode='categorical', shuffle=False
)

from tensorflow.keras import layers, models, optimizers, callbacks

# Load MobileNetV2
base_model = tf.keras.applications.MobileNetV2(weights='imagenet', include_top=False, input_shape=(224,224,3))

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.3),
    layers.Dense(8, activation='softmax')
])

model.summary()

# --- PHASE 1: PEMANASAN ---
base_model.trainable = False
model.compile(optimizer=optimizers.Adam(learning_rate=1e-3), loss='categorical_crossentropy', metrics=['accuracy'])

print("\n=== Phase 1: Pemanasan ===")
history1 = model.fit(train_gen, validation_data=val_gen, epochs=10)

# --- PHASE 2: FINE-TUNING (SANGAT DETAIL) ---
base_model.trainable = True
# Buka layer atas agar spesialis medis
for layer in base_model.layers[:100]: layer.trainable = False

model.compile(optimizer=optimizers.Adam(learning_rate=1e-5), loss='categorical_crossentropy', metrics=['accuracy'])

print("\n=== Phase 2: Fine-Tuning Spesialis Mata ===")
history2 = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=20,
    callbacks=[
        callbacks.EarlyStopping(patience=5, restore_best_weights=True),
        callbacks.ReduceLROnPlateau(factor=0.2, patience=2)
    ]
)

model.save('mobilenetv2_ocular_final.h5')

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix

# Prediksi
val_gen.reset()
y_pred = np.argmax(model.predict(val_gen), axis=1)
y_true = val_gen.classes
class_labels = list(val_gen.class_indices.keys())

# Plot Grafik
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history1.history['accuracy'] + history2.history['accuracy'], label='Accuracy')
plt.plot(history1.history['val_accuracy'] + history2.history['val_accuracy'], label='Val Acc')
plt.title('MobileNetV2 Accuracy Progress')
plt.legend()

# Classification Report
print("\n===== CLASSIFICATION REPORT MOBILE NET V2 =====")
print(classification_report(y_true, y_pred, target_names=class_labels))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', xticklabels=class_labels, yticklabels=class_labels)
plt.title('Confusion Matrix MobileNetV2')
plt.show()

# Download file untuk VS Code
from google.colab import files
files.download('mobilenetv2_ocular_final.h5')
files.download('label_encoder_mn.pkl')